/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public\models\airplane\model.glb
*/

import React, {useRef} from 'react'
import {useGLTF} from '@react-three/drei'
import {useFrame} from "@react-three/fiber";

const HELIX_SPEED = 4.5;

export function Airplane(props) {
    const {nodes, materials} = useGLTF('./models/airplane/model.glb')

    // Variable helix is used to rotate the propeller part model
    const helix = useRef();

    // useFrame is a React hook that allows us to re-render a component on each frame
    useFrame((_state, delta) => {
        helix.current.rotation.x += delta * HELIX_SPEED;
    });

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.PUSHILIN_Plane_Circle000.geometry}>
                <meshStandardMaterial color="white" />
            </mesh>
            <mesh
                ref={helix}
                geometry={nodes.PUSHILIN_Plane_Helix.geometry}
                material={materials.plane}
                position={[1.09, 0.23, 0]}
            >
                <meshStandardMaterial color="white" />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/airplane/model.glb');
