/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {useGLTF} from "@react-three/drei";
import React from "react";

export function Cloud_v2({opacity, ...props}) {
    const {nodes, materials} = useGLTF("./models/cloud_v2/model.glb");
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.secondballcloud001.geometry}>
                <meshStandardMaterial
                    {...materials["lambert2SG.001"]}
                    onBeforeCompile={(shader) => {
                        shader.fragmentShader = shader.fragmentShader
                            .replace(`vec4 diffuseColor = vec4( diffuse, opacity );`,
                                `
                                float fadeDistance = 200.0;
                                float dist = length(vViewPosition);
                                
                                float fadeOpacity = smoothstep(fadeDistance, 0.0, dist);
                                vec4 diffuseColor = vec4( diffuse, fadeOpacity * fadeOpacity );
                                `
                            );
                    }}
                    transparent
                    opacity={opacity}
                />
            </mesh>
        </group>
    );
}

useGLTF.preload("./models/cloud_v2/model.glb");
