/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import React from "react";

export function Cloud_v2({ opacity, ...props }) {
    const { nodes, materials } = useGLTF("./models/cloud_v2/model.glb");
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.secondballcloud001.geometry}>
                <meshStandardMaterial
                    {...materials["lambert2SG.001"]}
                    transparent
                    opacity={opacity}
                />
            </mesh>
        </group>
    );
}

useGLTF.preload("./models/cloud_v2/model.glb");
