/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import {useGLTF} from "@react-three/drei";
import React, {useRef} from "react";
import {fadeOnBeforeCompile} from "../utils/fadeMaterial.js";
import {useFrame} from "@react-three/fiber";

export function Cloud_v2({sceneOpacity, ...props}) {
    const {nodes, materials} = useGLTF("./models/cloud_v2/model.glb");
    const materialRef = useRef();

    useFrame(() => {
        materialRef.current.opacity = sceneOpacity.current;
    });

    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.secondballcloud001.geometry}>
                <meshStandardMaterial
                    ref={materialRef}
                    {...materials["lambert2SG.001"]}
                    onBeforeCompile={fadeOnBeforeCompile}
                    transparent
                />
            </mesh>
        </group>
    );
}

useGLTF.preload("./models/cloud_v2/model.glb");
