/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public\models\paper_airplane\model.glb
*/

import React from 'react'
import {useGLTF} from '@react-three/drei'

export function PaperAirplane(props) {
    const { nodes, materials } = useGLTF('./models/paper_airplane/model.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Plane.geometry} material={materials.White} />
        </group>
    )
}

useGLTF.preload('./models/paper_airplane/model.glb')
